<a href="https://colab.research.google.com/github/jayamadhavan2005/file/blob/master/daa_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Exp 1 Tower of Hanoi
def tower_of_hanoi(n, source, auxiliary, destination):
    if n == 1:
        print(f"Move disk 1 from {source} to {destination}")
        return
    tower_of_hanoi(n - 1, source, destination, auxiliary)
    print(f"Move disk {n} from {source} to {destination}")
    tower_of_hanoi(n - 1, auxiliary, source, destination)

# Example usage:
num_disks = 3
tower_of_hanoi(num_disks, 'A', 'B', 'C')


Move disk 1 from A to C
Move disk 2 from A to B
Move disk 1 from C to B
Move disk 3 from A to C
Move disk 1 from B to A
Move disk 2 from B to C
Move disk 1 from A to C


In [ ]:
#Exp 2.a Fibonacci Iterative
def fibonacci_iterative(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b

# Example usage:
fibonacci_iterative(10)


0 1 1 2 3 5 8 13 21 34 

In [1]:
#Exp 2.b Fibonacci Recursive
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

# Example usage:
terms = 10
for i in range(terms):
    print(fibonacci(i))

0
1
1
2
3
5
8
13
21
34


In [ ]:
#Exp 3 Bin packing
def first_fit_bin_packing(items, bin_capacity):
    bins = []  # List to hold the remaining space in each bin

    for item in items:
        # Try to fit item in an existing bin
        placed = False
        for i in range(len(bins)):
            if bins[i] >= item:
                bins[i] -= item
                placed = True
                break
        # If it doesn't fit in any bin, create a new one
        if not placed:
            bins.append(bin_capacity - item)

    return len(bins)

# Example usage:
items = [4, 8, 1, 4, 2, 1]  # Sizes of items
bin_capacity = 10
bins_used = first_fit_bin_packing(items, bin_capacity)

print(f"Number of bins used: {bins_used}")


Number of bins used: 2


In [2]:
#Exp 4 Fractional Knapsack
from fractions import Fraction

items = [(60, 10), (100, 20), (120, 30)]  # (value, weight)
capacity = 50

items.sort(key=lambda x: x[0]/x[1], reverse=True)
total_value = 0
taken = []

for value, weight in items:
    if capacity >= weight:
        capacity -= weight
        total_value += value
        taken.append((value, weight, Fraction(1)))
    else:
        fraction = Fraction(capacity, weight)
        total_value += value * float(fraction)
        taken.append((value, weight, fraction))
        break

print(f"Maximum Value: {total_value}\n")
print("Items taken:")
print(f"{'Value':<10}{'Weight':<10}{'Fraction'}")
for v, w, f in taken:
    print(f"{v:<10}{w:<10}{f.numerator}/{f.denominator}")

Maximum Value: 240.0

Items taken:
Value     Weight    Fraction
60        10        1/1
100       20        1/1
120       30        2/3


In [11]:
#Exp 5 Travelling Salesman Problem
from functools import lru_cache

# Distance matrix
graph = [
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
]
n = len(graph)

@lru_cache(None)
def tsp(pos, visited):
    if visited == (1 << n) - 1:
        return graph[pos][0], [0]
    min_cost, min_path = float('inf'), []
    for city in range(n):
        if not visited & (1 << city):
            cost, path = tsp(city, visited | (1 << city))
            cost += graph[pos][city]
            if cost < min_cost:
                min_cost, min_path = cost, [city] + path
    return min_cost, min_path

cost, path = tsp(0, 1)
print(f"Minimum Cost: {cost}")
print("Shortest Path:", ' -> '.join(map(str, [0] + path)))


Minimum Cost: 80
Shortest Path: 0 -> 1 -> 3 -> 2 -> 0


In [4]:
#Exp 6a Djikstra Algorithm
import heapq

def dijkstra(graph, start):
    dist, prev, pq = {v: float('inf') for v in graph}, {v: None for v in graph}, [(0, start)]
    dist[start] = 0
    while pq:
        d, u = heapq.heappop(pq)
        for v, w in graph[u]:
            if d + w < dist[v]:
                dist[v], prev[v] = d + w, u
                heapq.heappush(pq, (dist[v], v))
    return dist, prev

def shortest_path(prev, start, end):
    path, node = [], end
    while node and node != start:
        path.append(node)
        node = prev[node]
    return " -> ".join([start] + path[::-1]) if path else start

# Example usage
graph = {'A': [('B', 4), ('C', 2)], 'B': [('A', 4)], 'C': [('A', 2), ('D', 3)], 'D': [('C', 3)]}
start, end = 'A', 'D'
dist, prev = dijkstra(graph, start)

# Print table
print("Vertex  Previous Vertex  Distance from Start")
for v in graph:
    print(f"{v:6} {prev[v] if prev[v] else '-':15} {dist[v]}")

# Print shortest path
print(f"\nShortest path from {start} to {end}: {shortest_path(prev, start, end)}")
print(f"Shortest distance: {dist[end]}")


Vertex  Previous Vertex  Distance from Start
A      -               0
B      A               4
C      A               2
D      C               5

Shortest path from A to D: A -> C -> D
Shortest distance: 5


In [5]:
#Exp 6b Floyd Warshall Algorithm
import numpy as np
def floyd_warshall(graph):
    num_vertices = len(graph)
    distance = np.copy(graph)
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]
    return distance
graph = [
    [0, 1, np.inf],
    [1, 0, 2],
    [np.inf, 2, 0]
]

shortest_paths = floyd_warshall(graph)
print("Shortest path distance matrix:")
print(shortest_paths)

Shortest path distance matrix:
[[0. 1. 3.]
 [1. 0. 2.]
 [3. 2. 0.]]


In [6]:
#Exp 7a Prim algorithm
def prim(graph):
    n = len(graph)
    selected = [False] * n
    selected[0] = True
    edges, cost = [], 0

    for _ in range(n - 1):
        min_edge = (None, None, float('inf'))
        for u in range(n):
            if selected[u]:
                for v in range(n):
                    if not selected[v] and 0 < graph[u][v] < min_edge[2]:
                        min_edge = (u, v, graph[u][v])
        u, v, w = min_edge
        selected[v] = True
        edges.append((u, v, w))
        cost += w

    print("Edges in MST:")
    for u, v, w in edges:
        print(f"{u} - {v} : {w}")
    print(f"\nTotal Cost: {cost}")
    # Example usage
graph = [
    [0, 2, 0, 6, 0],
    [2, 0, 3, 8, 5],
    [0, 3, 0, 0, 7],
    [6, 8, 0, 0, 9],
    [0, 5, 7, 9, 0]
]

prim(graph)

Edges in MST:
0 - 1 : 2
1 - 2 : 3
1 - 4 : 5
0 - 3 : 6

Total Cost: 16


In [7]:
#Exp 7b Kruskal algorithm
class DisjointSet:
    def __init__(self, n):
        self.parent = list(range(n))
        self.rank = [0] * n

    def find(self, u):
        if self.parent[u] != u:
            self.parent[u] = self.find(self.parent[u])
        return self.parent[u]

    def union(self, u, v):
        root_u = self.find(u)
        root_v = self.find(v)

        if root_u != root_v:
            if self.rank[root_u] > self.rank[root_v]:
                self.parent[root_v] = root_u
            elif self.rank[root_u] < self.rank[root_v]:
                self.parent[root_u] = root_v
            else:
                self.parent[root_v] = root_u
                self.rank[root_u] += 1


def kruskal(vertices, edges):
    # Sort edges based on weight
    edges.sort(key=lambda x: x[2])

    ds = DisjointSet(len(vertices))
    mst_edges = []
    total_weight = 0

    for u, v, weight in edges:
        if ds.find(u) != ds.find(v):
            ds.union(u, v)
            mst_edges.append((u, v, weight))
            total_weight += weight

    return mst_edges, total_weight

def main():
    # Define the graph
    vertices = ['A', 'B', 'C', 'D', 'E']
    edges = [
        (0, 1, 4),  # A-B
        (0, 2, 1),  # A-C
        (1, 2, 2),  # B-C
        (1, 3, 5),  # B-D
        (2, 3, 8),  # C-D
        (3, 4, 3),  # D-E
        (2, 4, 7)   # C-E
    ]

    print("Vertices:", vertices)
    print("Edges (u, v, weight):", edges)

    mst_edges, total_weight = kruskal(vertices, edges)

    print("\nMinimum Spanning Tree (MST) Edges (u, v, weight):")
    for u, v, weight in mst_edges:
        print(f"({vertices[u]}, {vertices[v]}, {weight})")

    print("Total weight of MST:", total_weight)


if __name__ == "__main__":
    main()

Vertices: ['A', 'B', 'C', 'D', 'E']
Edges (u, v, weight): [(0, 1, 4), (0, 2, 1), (1, 2, 2), (1, 3, 5), (2, 3, 8), (3, 4, 3), (2, 4, 7)]

Minimum Spanning Tree (MST) Edges (u, v, weight):
(A, C, 1)
(B, C, 2)
(D, E, 3)
(B, D, 5)
Total weight of MST: 11


In [10]:
#Exp 8 Network flow
class Graph:
    def __init__(self, vertices):
        self.V = vertices  # Number of vertices
        self.graph = [[0] * vertices for _ in range(vertices)]  # Initialize graph with zero capacity

    # Function to perform DFS and check if there is a path from source to sink
    def dfs(self, s, t, parent):
        visited = [False] * self.V
        stack = [s]
        visited[s] = True

        while stack:
            u = stack.pop()

            for v in range(self.V):
                if visited[v] == False and self.graph[u][v] > 0:  # If v is not visited and there's a residual capacity
                    stack.append(v)
                    visited[v] = True
                    parent[v] = u

                    if v == t:
                        return True

        return False

    # Ford-Fulkerson algorithm to find the maximum flow
    def ford_fulkerson(self, source, sink):
        parent = [-1] * self.V  # Array to store the path
        max_flow = 0  # Start with zero flow
        all_paths = []  # To store the list of all augmenting paths

        # Augment the flow while there is a path from source to sink
        while self.dfs(source, sink, parent):
            path_flow = float('Inf')
            path = []  # To store the current augmenting path

            # Find the maximum flow through the path found by DFS
            s = sink
            while s != source:
                path.append(s)
                path_flow = min(path_flow, self.graph[parent[s]][s])
                s = parent[s]
            path.append(source)
            path.reverse()  # Reverse the path to show it from source to sink

            # Store the current augmenting path
            all_paths.append((path, path_flow))

            # Update the residual capacities of the edges and reverse edges along the path
            max_flow += path_flow
            v = sink
            while v != source:
                u = parent[v]
                self.graph[u][v] -= path_flow  # Reduce the capacity in the forward direction
                self.graph[v][u] += path_flow  # Add the capacity in the reverse direction
                v = parent[v]

        return max_flow, all_paths


# Example usage:
if __name__ == "__main__":
    # Create a graph and add edges
    g = Graph(6)  # A graph with 6 vertices (0 to 5)

    # Adding edges (u, v, capacity)
    g.graph[0][1] = 16
    g.graph[0][2] = 13
    g.graph[1][2] = 10
    g.graph[1][3] = 12
    g.graph[2][1] = 4
    g.graph[2][4] = 14
    g.graph[3][2] = 9
    g.graph[3][5] = 20
    g.graph[4][3] = 7
    g.graph[4][5] = 4

    source = 0
    sink = 5

    max_flow, all_paths = g.ford_fulkerson(source, sink)

    # Display the source, sink, maximum flow, and augmenting paths
    print(f"Source: {source}, Sink: {sink}")
    print(f"The maximum possible flow is: {max_flow}")

    print("\nAugmenting paths:")
    for i, (path, flow) in enumerate(all_paths):
        print(f"Path {i+1}: {path} with flow: {flow}")



Source: 0, Sink: 5
The maximum possible flow is: 23

Augmenting paths:
Path 1: [0, 2, 4, 5] with flow: 4
Path 2: [0, 2, 4, 3, 5] with flow: 7
Path 3: [0, 1, 3, 5] with flow: 12


In [8]:
#Exp 9 Randomized algorithm
import random
# Function to partition the array
def partition_left(arr, low, high):
  pivot = arr[high]
  i = low
  for j in range(low, high):
    if arr[j] <= pivot:
      arr[i], arr[j] = arr[j], arr[i]
      i += 1
      arr[i], arr[high] = arr[high], arr[i]
    return i
# Function to perform random partition
def partition_right(arr, low, high):
  r = random.randint(low, high)
  arr[r], arr[high] = arr[high], arr[r]
  return partition_left(arr, low, high)
# Recursive function for quicksort
def quicksort(arr, low, high):
  if low < high:
    p = partition_right(arr, low, high)
    quicksort(arr, low, p - 1)
    quicksort(arr, p + 1, high)
# Function to print the array
def printArray(arr):
  for element in arr:
    print(element, end=" ")
  print()
# Driver code
arr = [6, 4, 12, 8, 15, 16]
n = len(arr)
print("Original array:", end=" ")
printArray(arr)
quicksort(arr, 0, n - 1)
print("Sorted array:", end=" ")
printArray(arr)
quicksort(arr, 0, n - 1)
print("Sorted array:", end=" ")
printArray(arr)

Original array: 6 4 12 8 15 16 
Sorted array: 6 12 16 8 4 15 
Sorted array: 15 12 8 16 6 4 


In [9]:
#Exp 10 Approximation
MAX_VERTICES = 100
graph = [[0 for _ in range(MAX_VERTICES)] for _ in range(MAX_VERTICES)]
included = [False for _ in range(MAX_VERTICES)]
# Function to find Vertex Cover using the APPROX-VERTEX_COVER algorithm
def approx_vertex_cover(vertices, edges):
  edges_remaining = [row[:] for row in graph]
  while edges > 0:
    for i in range(vertices):
      for j in range(vertices):
        if edges_remaining[i][j]:
          u = i
          v = j
          break
    included[u] = included[v] = True
    for i in range(vertices):
      edges_remaining[u][i] = edges_remaining[i][u] = False
      edges_remaining[v][i] = edges_remaining[i][v] = False
    edges -= 2
# Driver Code
if __name__ == "__main__":
  vertices = 8
  edges = 10
  edges_data = [(1, 6), (1, 2), (1, 4), (2, 3), (2, 4),(6, 7), (4, 7), (7, 8), (3, 5), (8, 5)]
  for u, v in edges_data:
    graph[u][v] = graph[v][u] = 1
  approx_vertex_cover(vertices, edges)
  print("Vertex Cover:", end=" ")
  for i in range(1, vertices + 1):
    if included[i]:
      print(i, end=" ")
  print()


Vertex Cover: 1 3 4 5 6 7 
